package com.tmw.tracking.domain;

public enum PermissionType {

    SYSTEM_PERMISSIONS, LOGIN_APP, SYSTEM_CONFIG_MANAGEMENT, SYSTEM_MONITORING,
    COMPANIES_MAINTAIN, COMPANIES_MAINTAIN_CRUD,
    COMPANY_MANAGEMENT, COMPANY_MANAGE_ROLES, COMPANY_MANAGE_USERS,

    ORDER, ORDER_SHOW, ORDER_UPDATE,
        ORDER_DETAILS, ORDER_DETAILS_SHOW, ORDER_DETAILS_UPDATE,
    LOGISTIC, LOGISTIC_READ, LOGISTIC_UPDATE, LOGISTIC_1C_OPERATOR, LOGISTIC_WAREHOUSE, LOGISTIC_MOUNTER,

    DICTIONARY,
        DICT_GOODS, DICT_GOODS_SHOW, DICT_GOODS_UPDATE,
        DICT_STATION_CODE, DICT_STATION_CODE_SHOW, DICT_STATION_CODE_UPDATE,
        DICT_DRIVERS, DICT_DRIVERS_SHOW, DICT_DRIVERS_UPDATE,
        DICT_CONT_TYPES, DICT_CONT_TYPES_SHOW, DICT_CONT_TYPES_UPDATE,
        DICT_CONT_LINES, DICT_CONT_LINES_SHOW, DICT_CONT_LINES_UPDATE,

    SHOW_WORKFLOW,



}
