
package com.tmw.tracking.domain.flex.onec;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "getOrdersPortType", targetNamespace = "http://v8.1c.ru/8.1/data/core")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface GetOrdersPortType {


    /**
     * 
     * @param paramload
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetOrders", action = "http://v8.1c.ru/8.1/data/core#getOrders:GetOrders")
    @WebResult(targetNamespace = "http://v8.1c.ru/8.1/data/core")
    @RequestWrapper(localName = "GetOrders", targetNamespace = "http://v8.1c.ru/8.1/data/core", className = "com.tmw.tracking.domain.flex.onec.GetOrders")
    @ResponseWrapper(localName = "GetOrdersResponse", targetNamespace = "http://v8.1c.ru/8.1/data/core", className = "com.tmw.tracking.domain.flex.onec.GetOrdersResponse")
    public String getOrders(
        @WebParam(name = "paramload", targetNamespace = "http://v8.1c.ru/8.1/data/core")
        String paramload);

}
