
package com.tmw.tracking.domain.flex.onec;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "getOrders", targetNamespace = "http://v8.1c.ru/8.1/data/core", wsdlLocation = "http://flextank:flextank1993@10.1.0.250:8080/expeditor/ws/getOrders.1cws?wsdl")
public class GetOrders_Service
    extends Service
{

    private final static URL GETORDERS_WSDL_LOCATION;
    private final static WebServiceException GETORDERS_EXCEPTION;
    private final static QName GETORDERS_QNAME = new QName("http://v8.1c.ru/8.1/data/core", "getOrders");

    static {
        URL url = null;
        WebServiceException e = null;
        //try {
            url = GetOrders_Service.class.getResource("/getOrders.wsdl");
            //url = new URL("http://flextank:flextank1993@stoles.mx.od.ua:8088/expeditor/ws/getOrders.1cws?wsdl");
        /*} catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }*/
        GETORDERS_WSDL_LOCATION = url;
        GETORDERS_EXCEPTION = e;
    }

    public GetOrders_Service() {
        super(__getWsdlLocation(), GETORDERS_QNAME);
    }

    public GetOrders_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), GETORDERS_QNAME, features);
    }

    public GetOrders_Service(URL wsdlLocation) {
        super(wsdlLocation, GETORDERS_QNAME);
    }

    public GetOrders_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GETORDERS_QNAME, features);
    }

    public GetOrders_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GetOrders_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns GetOrdersPortType
     */
    @WebEndpoint(name = "getOrdersSoap")
    public GetOrdersPortType getGetOrdersSoap() {
        return super.getPort(new QName("http://v8.1c.ru/8.1/data/core", "getOrdersSoap"), GetOrdersPortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GetOrdersPortType
     */
    @WebEndpoint(name = "getOrdersSoap")
    public GetOrdersPortType getGetOrdersSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://v8.1c.ru/8.1/data/core", "getOrdersSoap"), GetOrdersPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GETORDERS_EXCEPTION!= null) {
            throw GETORDERS_EXCEPTION;
        }
        return GETORDERS_WSDL_LOCATION;
    }

}
