#!/bin/bash

set -e
sudo su

yum update -y

export JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF-8

CATALINA_HOME=/usr/share/tomcat7-codedeploy
TOMCAT_VERSION=8.5.82
TOMCAT7_EXISTS="false"

# Tar file name
TOMCAT7_CORE_TAR_FILENAME="apache-tomcat-$TOMCAT_VERSION.tar.gz"
# Download URL for Tomcat7 core
TOMCAT7_CORE_DOWNLOAD_URL="http://mirror.olnevhost.net/pub/apache/tomcat/tomcat-7/v$TOMCAT_VERSION/bin/$TOMCAT7_CORE_TAR_FILENAME"
# The top-level directory after unpacking the tar file
TOMCAT7_CORE_UNPACKED_DIRNAME="apache-tomcat-$TOMCAT_VERSION"


# Check whether there exists a valid instance
# of Tomcat7 installed at the specified directory
[[ -d $CATALINA_HOME ]] && { service tomcat7 status; } && {
    echo "Tomcat7 is already installed at $CATALINA_HOME. Skip reinstalling it."
    TOMCAT7_EXISTS="true"
}

if [$TOMCAT7_EXISTS=="false"]; then

# Clear install directory
if [ -d $CATALINA_HOME ]; then
    rm -rf $CATALINA_HOME
fi
mkdir -p $CATALINA_HOME

# Download the latest Tomcat7 version
cd /tmp
{ which wget; } || { yum install wget; }
wget $TOMCAT7_CORE_DOWNLOAD_URL
if [[ -d /tmp/$TOMCAT7_CORE_UNPACKED_DIRNAME ]]; then
    rm -rf /tmp/$TOMCAT7_CORE_UNPACKED_DIRNAME
fi
tar xzf $TOMCAT7_CORE_TAR_FILENAME

# Copy over to the CATALINA_HOME
cp -r /tmp/$TOMCAT7_CORE_UNPACKED_DIRNAME/* $CATALINA_HOME

# Install Java if not yet installed
{ which java; } || { yum install java; }

# Create the service init.d script
cat > /etc/init.d/tomcat7 <<'EOF'
#!/bin/bash
# description: Tomcat7 Start Stop Restart
# processname: tomcat7
PATH=$JAVA_HOME/bin:$PATH
export PATH
CATALINA_HOME='/usr/share/tomcat7-codedeploy'

case $1 in
start)
sh $CATALINA_HOME/bin/startup.sh
;;
stop)
sh $CATALINA_HOME/bin/shutdown.sh
;;
restart)
sh $CATALINA_HOME/bin/shutdown.sh
sh $CATALINA_HOME/bin/startup.sh
;;
esac
exit 0
EOF


# Change permission mode for the service script
chmod 755 /etc/init.d/tomcat7

fi



#mvn

wget http://repos.fedorapeople.org/repos/dchen/apache-maven/epel-apache-maven.repo -O /etc/yum.repos.d/epel-apache-maven.repo
sed -i s/\$releasever/6/g /etc/yum.repos.d/epel-apache-maven.repo
yum install -y apache-maven

rm -rf /tmp/deployment-artifact
cd /tmp
mkdir -p deployment-artifact


rm -rf /tmp/codedeploy-deployment-staging-area/
cd /tmp
mkdir -p codedeploy-deployment-staging-area

cp -rf /opt/codedeploy-agent/deployment-root/$DEPLOYMENT_GROUP_ID/$DEPLOYMENT_ID/deployment-archive/* /tmp/codedeploy-deployment-staging-area/

#build

export JAVA_HOME=/opt/jdk1.8.0_131

cd /tmp/codedeploy-deployment-staging-area/
mvn clean install -P$TRACKING-ENV
rm -rf /tmp/deployment-artifact/*
cp -rf ./web/target/tracking-rest-app.war /tmp/deployment-artifact/

