package com.tmw.tracking.web.service.util.error;

public enum ErrorCode {
    PARAMETER_IS_INVALID("VAL-1001"),
    ENTITY_NOT_FOUND("VAL-1002"),

    AUTH_ERROR_TOKEN_IS_INVALID("AUTH-1001"),
    AUTH_ERROR_TOKEN_IS_EXPIRED("AUTH-1002"),
    AUTH_ERROR_USER_OR_PASSWORD_IS_INVALID("AUTH-1003"),
    AUTH_ERROR_USER_NOT_FOUND("AUTH-1004"),
    AUTH_ERROR_DEVICE_IS_NULL("AUTH-1005"),
    AUTH_ERROR_DEVICE_NOT_FOUND("AUTH-1006"),
    AUTH_ERROR_DEVICE_NOT_CREATED("AUTH-1007"),
    AUTH_ERROR_DEVICE_STORE_ID_INCORRECT("AUTH-1008"),
    AUTH_ERROR_USER_IS_BLOCKED("AUTH-1009"),

    AUTH_ERROR_ACCOUNT_DISABLED("AUTH-1010"),
    AUTH_ERROR_RESET_PASSWORD("AUTH-1011"),
    AUTH_ERROR_ACCOUNT_EXPIRED("AUTH-1012"),
    AUTH_ERROR_PASSWORD_EXPIRED("AUTH-1013"),
    AUTH_ERROR_NOT_AN_ADMIN("AUTH-1015"),

    AUTH_ERROR_PERMISSION_DENIED("AUTH-1016"),

    AUTH_ERROR_VERSION("AUTH-1020"),
    INTERNAL_SERVER_ERROR("500"),
    OPTIMISTIC_LOCK_ERROR("DB-1");

    private final String code;

    ErrorCode(final String code){
        this.code = code;
    }

    public String getCode() {
        return code;
    }
}
