# oracle dialect
hibernate.dialect=org.hibernate.dialect.MySQLDialect

#security
origin.list.allowed=https://stoles.com.ua,http://10.101.103.137,http://artinlog.com

#cache authentication info for exclude requests to TIBCO side on login(in hours)
auth.cache.time=4

#mail
mail.smtp.from=tracking@example.com
# user and password must be null if no authentication
# do not remove empty keys, Guice will failure
mail.user=test@agro-log.com
mail.password=Zkryk3hdl
mail.smtp.host=agro-log.com
mail.smtp.port=25
mail.smtp.auth=true
mail.smtp.starttls.enable=false
mail.transport.protocol=smtp
mail.allow.send=true


#tracking server
tracking.server.login=admin
tracking.server.password=Zkryk3hdl
tracking.server.url=http://crawler.artinlog.com
tracking.server.track.api.url=crawler/track
tracking.server.auction.api.url=crawler/auction
tracking.server.port=

#tracking client
tracking.client.flex.1c.username=flextank
tracking.client.flex.1c.password=flextank1993

# thread pool
thread.size=20

# period in minutes
monitoring.period=720
job.user=tracking@so-track.com.ua

tmw.auth.token.expiration=720

page.default.size=10

#version
major.version=1.01
client.version=1.1


tracking.debug.mode=true
