calculator_parameter_cargo_max_weight=26000
calculator_parameter_cargo_max_length=11700
calculator_parameter_cargo_max_length_20DV=5200
calculator_parameter_cargo_max_width=2250
calculator_parameter_cargo_max_height=2600
calculator_parameter_cargo_min_weight=1
calculator_parameter_cargo_min_length=10
calculator_parameter_cargo_min_width=10
calculator_parameter_cargo_min_height=10

calculator_parameter_container_min_workload=18000
calculator_parameter_container_max_workload=28500
calculator_parameter_max_for_3d=2000
